sudo apt update && sudo apt upgrade
sudo apt remove moby-buildx moby-cli moby-compose moby-containerd moby-engine moby-runc podman buildah skopeo containers-common temurin-*-jdk adoptopenjdk-* adoptium-ca-certificates openjdk-* ant ant-optional postgresql-* libpq-dev libmysqlclient* msodbcsql* mssql-tools unixodbc-dev mysql-client* mysql-common mysql-server* php*-*sql sphinxsearch mongodb* firefox google-chrome-stable microsoft-edge-stable xvfb apache2 apache2-* nginx nginx-* php-* php7* php8* session-manager-plugin azure-cli google-cloud-sdk gh subversion mercurial vim vim-* dotnet* aspnetcore* mono-* mono* libmono-* libmono* monodoc* msbuild nuget ruby* rake ri g++-10 g++-12 gcc-10 gcc-12 gfortran-* clang-* libclang* llvm-* libllvm* lldb-* lld-* clang-format-* clang-tidy-* powershell r-base* r-cran* r-doc* r-recommended snapd man-db manpages libgtk-3-* ubuntu-mono *-icon-theme esl-erlang imagemagick imagemagick-6-common libgl1-mesa-dri firebird* hhvm python python2
sudo rm -rfv /home/linuxbrew
sudo rm -rfv /usr/bin/docker-credential-ecr-login
sudo rm -rfv /usr/local/bin/docker-compose
sudo rm -rfv /usr/bin/docker-credential-ecr-login
sudo rm -rfv /usr/local/bin/kind
sudo rm -rfv /usr/local/bin/kubectl
sudo rm -rfv /usr/local/bin/minikube
sudo rm -rfv /usr/local/bin/kusomize
sudo rm -rfv /usr/local/bin/helm
sudo rm -rfv /usr/local/bin/terraform
sudo rm -rfv /usr/local/lib/android/sdk/build-tools
sudo rm -rfv /usr/local/lib/android/sdk/cmdline-tools
sudo rm -rfv /usr/local/lib/android/sdk/cmake
sudo rm -rfv /usr/local/lib/android/sdk/emulator
sudo rm -rfv /usr/local/lib/android/sdk/licenses
sudo rm -rfv /usr/local/lib/android/sdk/extras
sudo rm -rfv /usr/local/lib/android/sdk/ndk
sudo rm -rfv /usr/local/lib/android/sdk/patcher
sudo rm -rfv /usr/local/lib/android/sdk/platorm-tools
sudo rm -rfv /usr/local/lib/android/sdk/tools
sudo rm -rfv /usr/local/lib/android/sdk/platforms
sudo rm -rfv /usr/local/lib/android
sudo rm -rfv /usr/lib/jvm/
sudo rm -rfv /usr/local/graalvm
sudo rm -rfv /usr/share/java/selenium-server.jar
sudo rm -rfv /usr/share/gradle-8.0.2
sudo rm -rfv /usr/bin/gradle
sudo rm -rfv /usr/share/apache-maven-3.8.8
sudo rm -rfv /usr/bin/mvn
sudo rm -rfv /usr/share/mysql\*
sudo rm -rfv /opt/mssql-tools
sudo rm -rfv /usr/lib/firefox
sudo rm -rfv /usr/local/sqlpackage
sudo rm -rfv /usr/local/share/gecko_driver
sudo rm -rfv /usr/bin/google-chrome
sudo rm -rfv /usr/bin/geckodriver
sudo rm -rfv /usr/local/share/chrome_driver
sudo rm -rfv /usr/bin/chromedriver
sudo rm -rfv /usr/local/share/chromium
sudo rm -rfv /usr/bin/chromium-browser
sudo rm -rfv /usr/bin/chromium
sudo rm -rfv /usr/local/share/edge_driver
sudo rm -rfv /usr/bin/msedgedriver
sudo rm -rfv /usr/share/php
sudo rm -rfv /etc/php
sudo rm -rfv /usr/local/bin/phpunit
sudo rm -rfv /usr/bin/composer
sudo rm -rfv /home/runner/.config/composer
sudo rm -rfv /etc/.composer
sudo rm -rfv /etc/skel/.composer
sudo rm -rfv /usr/local/bin/aliyun
sudo rm -rfv /usr/local/bin/aws
sudo rm -rfv /usr/local/bin/aws_completer
sudo rm -rfv /usr/local/aws
sudo rm -rfv /usr/local/aws-cli
sudo rm -rfv /usr/local/bin/azcopy
sudo rm -rfv /usr/local/bin/azcopy10
sudo rm -rfv /usr/share/az_3.1.0.zip
sudo rm -rfv /usr/share/az_4.4.0.zip
sudo rm -rfv /usr/share/az_5.9.0.zip
sudo rm -rfv /usr/share/az_6.6.0.zip
sudo rm -rfv /usr/share/az_7.5.0.zip
sudo rm -rfv /usr/share/az_9.3.0
sudo rm -rfv /opt/az
sudo rm -rfv /usr/bin/az
sudo rm -rfv /usr/share/google-cloud-sdk
sudo rm -rfv /usr/local/bin/bicep
sudo rm -rfv /usr/local/bin/oc
sudo rm -rfv /usr/local/bin/oras
sudo rm -rfv /usr/local/bin/hub
sudo rm -rfv /usr/share/dotnet
sudo rm -rfv /home/runner/.dotnet
sudo rm -rfv /etc/skel/.dotnet/tools
sudo rm -rfv /etc/.dotnet/tools
sudo rm -rfv /usr/local/aws-sam-cli
sudo rm -rfv /usr/local/bin/vcpkg
sudo rm -rfv /usr/share/ri
sudo rm -rfv /usr/local/n
sudo rm -rfv /usr/local/bin/n
sudo rm -rfv /usr/local/lib/node_modules
sudo rm -rfv /etc/skel/.nvm
sudo rm -rfv /home/runner/.nvm
sudo rm -rfv /opt/pipx
sudo rm -rfv /opt/pipx_bin
sudo rm -rfv /opt/hostedtoolcache/CodeQL
sudo rm -rfv /opt/hostedtoolcache/Java_Adopt_jdk
sudo rm -rfv /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk
sudo rm -rfv /opt/hostedtoolcache/PyPy
sudo rm -rfv /opt/hostedtoolcache/Python
sudo rm -rfv /opt/hostedtoolcache/Ruby
sudo rm -rfv /usr/local/share/vcpkg
sudo rm -rfv /opt/hostedtoolcache/node
sudo rm -rfv /usr/lib/llvm-10
sudo rm -rfv /usr/local/bin/ccmake
sudo rm -rfv /usr/local/bin/cmake
sudo rm -rfv /usr/local/bin/cmake-gui
sudo rm -rfv /usr/local/bin/ctest
sudo rm -rfv /usr/local/bin/cpack
sudo rm -rfv /usr/local/share/cmake-3.26
sudo rm -rfv /usr/local/\*cmake\*
sudo rm -rfv /usr/local/bin/ccmake
sudo rm -rfv /usr/local/bin/cmake
sudo rm -rfv /usr/local/bin/cmake-gui
sudo rm -rfv /opt/hostedtoolcache/go
sudo rm -rfv /usr/local/doc/cmake
sudo rm -rfv /usr/local/share/cmake-3.26
sudo rm -rfv /opt/microsoft/powershell
sudo rm -rfv /usr/share/rust
sudo rm -rfv /home/runner/.cargo
sudo rm -rfv /home/runner/.rustup
sudo rm -rfv /etc/skel/.rustup
sudo rm -rfv /etc/skel/.cargo
sudo rm -rfv /etc/.rustup
sudo rm -rfv /etc/.cargo
sudo rm -rfv /usr/local/bin/stack
sudo rm -rfv /home/runner/.ghcup
sudo rm -rfv /usr/local/.ghcup
sudo rm -rfv /usr/share/kotlinc
sudo rm -rfv /usr/bin/kotlin
sudo rm -rfv /usr/bin/kotlin-dce-js
sudo rm -rfv /usr/local/share/powershell
sudo rm -rfv /usr/bin/kotlinc
sudo rm -rfv /usr/bin/kotlinc-js
sudo rm -rfv /usr/bin/kotlinc-jvm
sudo rm -rfv /usr/bin/julia
sudo rm -rfv /usr/share/swift
sudo rm -rfv /usr/local/bin/swift
sudo rm -rfv /usr/local/bin/swiftc
sudo rm -rfv /var/cache/snapd
sudo rm -rfv /home/runner/snap
sudo rm -rfv /usr/local/bin/rebar3
sudo rm -rfv /usr/share/firebird\*
sudo rm -rfv /opt/hhvm
sudo rm -rfv /usr/share/sbt
sudo rm -rfv /usr/bin/sbt
sudo rm -rfv /usr/local/share/phantomjs-2.1.1-linux-x86_64
sudo rm -rfv /usr/local/bin/phantomjs
sudo rm -rfv /usr/local/bin/packer
sudo rm -rfv /usr/local/lib/lein
sudo rm -rfv /usr/local/bin/lein
sudo rm -rfv /usr/local/bin/pulumi
sudo rm -rfv /usr/local/bin/pulumi-analyzer-policy
sudo rm -rfv /usr/local/bin/pulumi-analyzer-policy-python
sudo rm -rfv /usr/local/bin/pulumi-language-dotnet
sudo rm -rfv /usr/local/bin/pulumi-language-go
sudo rm -rfv /usr/local/bin/pulumi-language-java
sudo rm -rfv /usr/local/bin/pulumi-language-nodejs
sudo rm -rfv /usr/local/bin/pulumi-language-python
sudo rm -rfv /usr/local/bin/pulumi-language-python-exec
sudo rm -rfv /usr/local/bin/pulumi-language-yaml
sudo rm -rfv /usr/local/bin/pulumi-resource-pulumi-nodejs
sudo rm -rfv /usr/local/bin/pulumi-resource-pulumi-python
sudo rm -rfv /usr/local/bin/pulumi-watch
sudo rm -rfv /usr/local/julia1.8.5
sudo rm -rfv /usr/bin/conda
sudo rm -rfv /usr/share/miniconda
sudo rm -rfv /usr/share/dotnet
sudo rm -rfv /opt/ghc
sudo rm -rfv /usr/local/share/boost
sudo rm -rfv "$AGENT_TOOLSDIRECTORY"
df -h
