name: GitHub Workflows
on:
  workflow_dispatch:
    inputs:
      CM:
        description: 'Enter Command'
        required: true
        default: ''
      OF1:
        description: 'Output File 1'
        required: false
        default: ''
      OF2:
        description: 'Output File 2'
        required: false
        default: ''
      OF3:
        description: 'Output File 3'
        required: false
        default: ''
      OF4:
        description: 'Output File 4'
        required: false
        default: ''
      OF5:
        description: 'Output File 5'
        required: false
        default: ''
      OF6:
        description: 'Output File 6'
        required: false
        default: ''
      OF7:
        description: 'Output File 7'
        required: false
        default: ''
jobs:
  Actions:
    runs-on: ubuntu-20.04
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Running Command
        run: ${{ inputs.CM }}
        continue-on-error: true

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Exported File
          path: |
            /home/runner/work/GitHub_Workflows/GitHub_Workflows/${{ inputs.OF1 }}
            /home/runner/work/GitHub_Workflows/GitHub_Workflows/${{ inputs.OF2 }}
            /home/runner/work/GitHub_Workflows/GitHub_Workflows/${{ inputs.OF3 }
            /home/runner/work/GitHub_Workflows/GitHub_Workflows/${{ inputs.OF4 }}
            /home/runner/work/GitHub_Workflows/GitHub_Workflows/${{ inputs.OF5 }}
            /home/runner/work/GitHub_Workflows/GitHub_Workflows/${{ inputs.OF6 }}
            /home/runner/work/GitHub_Workflows/GitHub_Workflows/${{ inputs.OF7 }}
