name: GitHub Workflows
on:
  workflow_dispatch:
    inputs:
      OS:
        description: 'Operation System'
        required: true
        default: 'ubuntu-20.04'
        type: choice
        options:
          - 'windows-2019'
          - 'windows-2022'
          - 'windows-latest'
          - 'ubuntu-20.04'
          - 'ubuntu-22.04'
          - 'ubuntu-latest'
          - 'macos-11'
          - 'macos-12-xl'
          - 'macos-latest-xl'
          - 'macos-12'
          - 'macos-latest'
          - 'macos-13-xl'
          - 'macos-13'
      FS:
        description: 'Do you want to free up space before running? (This process takes about 5 minutes)'
        required: true
        default: 'no'
        type: choice
        options:
          - 'no'
          - 'yes'
      ERROR:
        description: 'Keep running when command fails?'
        required: true
        default: 'true'
        type: choice
        options:
          - 'false'
          - 'true'
      CM1:
        description: 'Command 1'
        required: false
      CM2:
        description: 'Command 2'
        required: false
      CM3:
        description: 'Command 3'
        required: false
      CM4:
        description: 'Command 4'
        required: false
      CM5:
        description: 'Command 5'
        required: false
      CM6:
        description: 'Command 6'
        required: false
      PATH:
        description: 'Export file (File/Folder)'
        required: false
jobs:
  Actions:
    runs-on: ${{ inputs.OS }}
    permissions: read-all|write-all
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Free up space: ${{ inputs.FS }}
        run: bash sh/${{ inputs.FS }}.sh
        continue-on-error: ${{ inputs.ERROR }}

      - name: Running Command 1
        run: ${{ inputs.CM1 }}
        continue-on-error: ${{ inputs.ERROR }}

      - name: Running Command 2
        run: ${{ inputs.CM2 }}
        continue-on-error: ${{ inputs.ERROR }}
        
      - name: Running Command 3
        run: ${{ inputs.CM3 }}
        continue-on-error: ${{ inputs.ERROR }}
        
      - name: Running Command 4
        run: ${{ inputs.CM4 }}
        continue-on-error: ${{ inputs.ERROR }}
        
      - name: Running Command 5
        run: ${{ inputs.CM5 }}
        continue-on-error: ${{ inputs.ERROR }}

      - name: Running Command 6
        run: ${{ inputs.CM6 }}
        continue-on-error: ${{ inputs.ERROR }}

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Exported File
          path: ${{ inputs.PATH }}
