name: Kernel Builder (v1)
on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'Manifest Branch'
        required: true
        default: 'common-android-4.19-stable'
      KERNEL_URL:
        description: 'Kernel Source URL'
        required: true
        default: 'https://github.com/VThang51/android_kernel_samsung_a13xx'
      KERNEL_BRANCH:
        description: 'Kernel Source Branch'
        required: true
        default: 'A135FXXU3CWB9'
      KERNEL_PATH:
        description: 'Kernel Source Path'
        required: true
        default: 'device/samsung/a13xx'
      BUILD_COMMAND:
        description: 'Build Command'
        required: true
        default: 'export PLATFORM_VERSION=13 && export ARCH=arm64 && make exynos850-a13xx_defconfig && make'
jobs:
  Kernel-Builder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Run sudo.sh
        run: bash sh/sudo.sh -freespace -setuptwrp

      - name: Git Config
        run: |
          mkdir android-kernel
          cd android-kernel
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Sync Manifest
        run: |
          cd android-kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b ${{ inputs.MANIFEST_BRANCH }}

      - name: Sync Source
        run: |
          cd android-kernel
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          rm -rf .rep

      - name: Clone Kernel Source
        run: |
          git clone -b ${{ inputs.KERNEL_BRANCH }} ${{ inputs.KERNEL_URL }} android-kernel/${{ inputs.KERNEL_PATH }}

      - name: Compile Custom Recovery 
        run: |
          cd android-kernel
          build/build.sh
          ${{ inputs.BUILD_COMMAND }}

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Kernel
          path: android-kernel/out/${{ inputs.MANIFEST_BRANCH }}/dist
