name: Kernel Builder
on: push
jobs:
  Buiding-Kernel:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Setup Environment
      run: |
        sudo apt update
        sudo apt install git make bison flex

    - name: Clone Kernel Source
      run: |
        git clone https://github.com/VThang51/android_kernel_samsung_a13xx.git -b VThang51-patch-touchfix kernel

    - name: Clone Toolchain
      run: |
        cd kernel
        git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 -b android-msm-redbull-4.19-android14 toolchain/clang/host/linux-x86
        git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-msm-redbull-4.19-android14 toolchain/gcc/linux-x86/aarch64/aarch64-linux-android-4.9

    - name: Building Kernel
      run: |
        cd kernel
        sudo chmod 755 build_kernel.sh
        ./build_kernel.sh

    - uses: actions/upload-artifact@v4
      with:
        name: Exported File
        path: |
          kernel/arch/arm64/boot/Image
          kernel/arch/arm64/boot/Image.gz
          kernel/drivers/*/*.ko
